{
    "name": "Darakjian - Zebra Tag Printing",
    "version": "19.0.19.9.2",
    "summary": "Print jewelry tags on Zebra printers straight from the browser",
    "category": "Inventory",
    "author": "Yaguven C.G.",
    "website": "https://github.com/Darakjian/yaguven_darakjian_etiquetas",
    "depends": ["product", "stock", "purchase"],
    "data": [
        "security/ir.model.access.csv",
        "data/tag_cells.xml",
        "views/tag_config_views.xml",
        "views/product_wizard_views.xml",
        "views/guided_create_views.xml",
        "views/purchase_guided_views.xml",
        "views/product_views.xml",
        "views/stock_lot_views.xml",
        "views/stock_picking_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "yaguven_darakjian_etiquetas/static/src/js/print_label_button.js",
            "yaguven_darakjian_etiquetas/static/src/js/guided_create.js",
            "yaguven_darakjian_etiquetas/static/src/xml/print_label_button.xml",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
